name: Coding Standards

on:
  pull_request:
    branches:
      - main

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2,cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist --optimize-autoloader

      - name: Check code style
        run: composer phpcs -- --format=checkstyle | cs2pr
