name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    name: Release
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}
          package-name: ""
          release-type: php
          default-branch: main
