name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    name: Release
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release-type: php
          default-branch: main
